import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home({name}) {

  let [data,setData]=useState(null)

  let customFetch = async () =>{
    let res= await fetch("https://logger-git-main-eddarv.vercel.app/api")
    let data= res.body
    setData(data)
  }

  useEffect(()=>{
    customFetch()

  },[])

  useEffect(()=>{
    console.log(data)

  },[data])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {name}
        </h1>

        
      </main>

    
    </div>
  )
}


export async function getServerSideProps({ req, res }) {

  let name = []
  name=[...name,`${Math.random()*10}`]

  return {
    props: {
      name
    }
  };
}